services:
  - type: web
    name: sib-backend
    env: python
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.11.9